"""The preset theme catalogue: one dict per selectable preset (slug, label,
era, colour language, paired icon pack, token overrides).

Split out of ``preset_themes`` in the v11 cycle (H-D.4) as a pure move. Data
only; the generator that writes presets to the themes volume stays in
``preset_themes``, which re-exports ``PRESET_THEMES``.
"""




# Folder slug must match how preferences / theme_asset resolve paths.
# Wave 2d: each preset owns a colour language *and* a paired icon pack
# (plus --od-icon-* token overrides) so packs are not near-identical hues.
# Avoid warm orange accents that clash with the default green system chrome.
PRESET_THEMES = [
    {
        'slug': 'aurora',
        'name': 'Arcade Neon',
        'description': '8-bit cabinet — square corners, tight tiles, CRT scan.',
        'group': 'cabinet',
        'era': 'arcade_cabinet',
        'btn_primary': '#22d3ee',
        'btn_primary_hover': '#06b6d4',
        'bg_dark_40': 'rgba(10, 24, 32, 0.94)',
        'bg_dark_30': 'rgba(6, 16, 24, 0.97)',
        'icon_pack': 'pixel',
        'tokens': {
            'od-text': '#e0f7fa',
            'od-text-muted': '#7dd3e8',
            'od-border': 'rgba(34, 211, 238, 0.22)',
            'od-accent-2': '#a5f3fc',
            'od-glass-bg': 'rgba(6, 28, 36, 0.78)',
            'od-glass-border': 'rgba(34, 211, 238, 0.28)',
            'od-glass-blur': '10px',
            'od-crt-opacity': '0.09',
            'od-tile-gap': '8px',
            'font-display': '"Lucida Console", "Courier New", monospace',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '2.75',
            'od-icon-linecap': 'square',
            'od-icon-linejoin': 'miter',
            'od-icon-fill': 'none',
            'od-icon-fill-opacity': '0',
        },
    },
    {
        'slug': 'ember',
        'name': 'Hot Cabinet',
        'description': 'Coin-op cabinet — pill chips, deep shadow, filled glyphs.',
        'group': 'cabinet',
        'era': 'arcade_cabinet',
        'btn_primary': '#f472b6',
        'btn_primary_hover': '#ec4899',
        'bg_dark_40': 'rgba(28, 10, 22, 0.94)',
        'bg_dark_30': 'rgba(18, 6, 14, 0.97)',
        'icon_pack': 'filled',
        'tokens': {
            'od-text': '#fce7f3',
            'od-text-muted': '#f9a8d4',
            'od-border': 'rgba(244, 114, 182, 0.24)',
            'od-accent-2': '#fb7185',
            'od-glass-bg': 'rgba(36, 8, 24, 0.8)',
            'od-glass-border': 'rgba(244, 114, 182, 0.3)',
            'od-glass-blur': '14px',
            'od-crt-opacity': '0.06',
            'od-tile-gap': '10px',
            'font-display': '"Arial Black", "Segoe UI", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '1.25',
            'od-icon-linecap': 'round',
            'od-icon-linejoin': 'round',
            'od-icon-fill': 'currentColor',
            'od-icon-fill-opacity': '0.92',
        },
    },
    {
        'slug': 'violet',
        'name': 'Modern Violet',
        'description': 'Sixth-gen glass — large radius, heavy blur, thin strokes.',
        'group': 'cabinet',
        'era': 'media_center_00s',
        'btn_primary': '#a78bfa',
        'btn_primary_hover': '#8b5cf6',
        'bg_dark_40': 'rgba(22, 16, 36, 0.94)',
        'bg_dark_30': 'rgba(14, 10, 28, 0.97)',
        'icon_pack': 'soft',
        'tokens': {
            'od-text': '#f5f3ff',
            'od-text-muted': '#c4b5fd',
            'od-border': 'rgba(167, 139, 250, 0.2)',
            'od-accent-2': '#c4b5fd',
            'od-glass-bg': 'rgba(24, 16, 48, 0.7)',
            'od-glass-border': 'rgba(167, 139, 250, 0.26)',
            'od-glass-blur': '18px',
            'od-crt-opacity': '0.02',
            'od-tile-gap': '12px',
            'font-display': '"Segoe UI Semibold", "Segoe UI", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '1.35',
            'od-icon-linecap': 'round',
            'od-icon-linejoin': 'round',
            'od-icon-fill': 'none',
            'od-icon-fill-opacity': '0',
        },
    },
    {
        'slug': 'forest',
        'name': 'Vector Green',
        'description': 'Vector monitor — zero radius, tight type, phosphor green.',
        'group': 'cabinet',
        'era': 'desk',
        'btn_primary': '#4ade80',
        'btn_primary_hover': '#22c55e',
        'bg_dark_40': 'rgba(12, 24, 18, 0.94)',
        'bg_dark_30': 'rgba(8, 16, 12, 0.97)',
        'icon_pack': 'outline',
        'tokens': {
            'od-text': '#ecfdf5',
            'od-text-muted': '#86efac',
            'od-border': 'rgba(74, 222, 128, 0.18)',
            'od-accent-2': '#86efac',
            'od-glass-bg': 'rgba(8, 28, 16, 0.88)',
            'od-glass-border': 'rgba(74, 222, 128, 0.22)',
            'od-glass-blur': '6px',
            'od-crt-opacity': '0.07',
            'od-tile-gap': '9px',
            'font-display': '"Courier New", "Lucida Console", monospace',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '2',
            'od-icon-linecap': 'butt',
            'od-icon-linejoin': 'miter',
            'od-icon-fill': 'none',
            'od-icon-fill-opacity': '0',
        },
    },
    {
        'slug': 'ocean',
        'name': 'Modern Ocean',
        'description': 'Seventh-gen chrome — medium radius, duotone fill.',
        'group': 'cabinet',
        'era': 'media_center_00s',
        'btn_primary': '#3b82f6',
        'btn_primary_hover': '#2563eb',
        'bg_dark_40': 'rgba(10, 18, 36, 0.94)',
        'bg_dark_30': 'rgba(6, 12, 28, 0.97)',
        'icon_pack': 'duotone',
        'tokens': {
            'od-text': '#eff6ff',
            'od-text-muted': '#93c5fd',
            'od-border': 'rgba(59, 130, 246, 0.2)',
            'od-accent-2': '#60a5fa',
            'od-glass-bg': 'rgba(8, 20, 44, 0.74)',
            'od-glass-border': 'rgba(59, 130, 246, 0.28)',
            'od-glass-blur': '14px',
            'od-crt-opacity': '0.015',
            'od-tile-gap': '11px',
            'font-display': '"Segoe UI", "Helvetica Neue", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '1.75',
            'od-icon-linecap': 'round',
            'od-icon-linejoin': 'round',
            'od-icon-fill': 'currentColor',
            'od-icon-fill-opacity': '0.22',
        },
    },
    {
        'slug': 'rose',
        'name': 'Modern Rose',
        'description': 'Handheld — compact space, serif display, soft strokes.',
        'group': 'cabinet',
        'era': 'teen_bedroom_90s',
        'btn_primary': '#fb7185',
        'btn_primary_hover': '#f43f5e',
        'bg_dark_40': 'rgba(28, 14, 20, 0.94)',
        'bg_dark_30': 'rgba(18, 8, 14, 0.97)',
        'icon_pack': 'soft',
        'tokens': {
            'od-text': '#fff1f2',
            'od-text-muted': '#fda4af',
            'od-border': 'rgba(251, 113, 133, 0.2)',
            'od-accent-2': '#fda4af',
            'od-glass-bg': 'rgba(32, 12, 20, 0.72)',
            'od-glass-border': 'rgba(251, 113, 133, 0.26)',
            'od-glass-blur': '16px',
            'od-crt-opacity': '0.025',
            'od-tile-gap': '12px',
            'font-display': '"Georgia", "Times New Roman", serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '1.4',
            'od-icon-linecap': 'round',
            'od-icon-linejoin': 'round',
            'od-icon-fill': 'none',
            'od-icon-fill-opacity': '0',
        },
    },
    {
        'slug': 'mono',
        'name': 'Modern Mono',
        'description': 'Home computer — 0 radius, no shadow, dense mono blocks.',
        'group': 'cabinet',
        'era': 'desk',
        'btn_primary': '#94a3b8',
        'btn_primary_hover': '#64748b',
        'bg_dark_40': 'rgba(18, 18, 22, 0.94)',
        'bg_dark_30': 'rgba(10, 10, 14, 0.97)',
        'icon_pack': 'mono',
        'tokens': {
            'od-text': '#f8fafc',
            'od-text-muted': '#94a3b8',
            'od-border': 'rgba(148, 163, 184, 0.18)',
            'od-accent-2': '#cbd5e1',
            'od-glass-bg': 'rgba(16, 16, 20, 0.82)',
            'od-glass-border': 'rgba(255, 255, 255, 0.1)',
            'od-glass-blur': '8px',
            'od-crt-opacity': '0.01',
            'od-tile-gap': '10px',
            'font-display': '"Segoe UI", "Helvetica Neue", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '0.5',
            'od-icon-linecap': 'square',
            'od-icon-linejoin': 'miter',
            'od-icon-fill': 'currentColor',
            'od-icon-fill-opacity': '1',
        },
    },
    {
        'slug': 'sunset',
        'name': 'Coin Gold',
        'description': 'Medal cabinet — warm gold, large shadow, chunky type.',
        'group': 'cabinet',
        'era': 'wood_den_80s',
        'btn_primary': '#fbbf24',
        'btn_primary_hover': '#eab308',
        'bg_dark_40': 'rgba(24, 18, 8, 0.94)',
        'bg_dark_30': 'rgba(14, 10, 4, 0.97)',
        'icon_pack': 'filled',
        'tokens': {
            'od-text': '#fffbeb',
            'od-text-muted': '#fcd34d',
            'od-border': 'rgba(251, 191, 36, 0.22)',
            'od-accent-2': '#fde68a',
            'od-glass-bg': 'rgba(28, 20, 6, 0.8)',
            'od-glass-border': 'rgba(251, 191, 36, 0.3)',
            'od-glass-blur': '12px',
            'od-crt-opacity': '0.08',
            'od-tile-gap': '8px',
            'font-display': '"Arial Black", "Impact", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '1.5',
            'od-icon-linecap': 'round',
            'od-icon-linejoin': 'round',
            'od-icon-fill': 'currentColor',
            'od-icon-fill-opacity': '0.88',
        },
    },
    {
        'slug': 'ice',
        'name': 'Modern Ice',
        'description': 'HD-era frost — max radius, airy space, high blur.',
        'group': 'cabinet',
        'era': 'media_center_00s',
        'btn_primary': '#7dd3fc',
        'btn_primary_hover': '#38bdf8',
        'bg_dark_40': 'rgba(12, 20, 32, 0.94)',
        'bg_dark_30': 'rgba(8, 14, 24, 0.97)',
        'icon_pack': 'soft',
        'tokens': {
            'od-text': '#f0f9ff',
            'od-text-muted': '#7dd3fc',
            'od-border': 'rgba(125, 211, 252, 0.2)',
            'od-accent-2': '#bae6fd',
            'od-glass-bg': 'rgba(10, 22, 40, 0.68)',
            'od-glass-border': 'rgba(125, 211, 252, 0.28)',
            'od-glass-blur': '20px',
            'od-crt-opacity': '0.02',
            'od-tile-gap': '12px',
            'font-display': '"Segoe UI Light", "Segoe UI", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '1.25',
            'od-icon-linecap': 'round',
            'od-icon-linejoin': 'round',
            'od-icon-fill': 'none',
            'od-icon-fill-opacity': '0',
        },
    },
    {
        'slug': 'era-80s',
        'name': '1980s wood den',
        'description': 'Family television, wood panel, harvest lamp — when a lot of households started.',
        'group': 'decade',
        'era': 'wood_den_80s',
        'btn_primary': '#e8c07d',
        'btn_primary_hover': '#d4a85c',
        'bg_dark_40': 'rgba(26, 20, 16, 0.88)',
        'bg_dark_30': 'rgba(14, 10, 8, 0.92)',
        'icon_pack': 'pixel',
        'tokens': {
            'od-text': '#f4e6d0',
            'od-text-muted': '#c8a878',
            'od-border': 'rgba(232, 192, 125, 0.22)',
            'od-accent-2': '#ffb765',
            'od-glass-bg': 'rgba(28, 18, 12, 0.72)',
            'od-glass-border': 'rgba(232, 192, 125, 0.28)',
            'od-glass-blur': '6px',
            'od-crt-opacity': '0.1',
            'od-tile-gap': '8px',
            'font-display': '"Press Start 2P", "Lucida Console", monospace',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '2.5',
            'od-icon-linecap': 'square',
            'od-icon-linejoin': 'miter',
            'od-icon-fill': 'none',
            'od-icon-fill-opacity': '0',
        },
    },
    {
        'slug': 'era-90s',
        'name': '1990s teen bedroom',
        'description': 'Posters, carpet, afternoon window — 16-bit on the floor.',
        'group': 'decade',
        'era': 'teen_bedroom_90s',
        'btn_primary': '#c9a0d4',
        'btn_primary_hover': '#b084c0',
        'bg_dark_40': 'rgba(28, 21, 36, 0.88)',
        'bg_dark_30': 'rgba(16, 12, 22, 0.92)',
        'icon_pack': 'filled',
        'tokens': {
            'od-text': '#f3e8f8',
            'od-text-muted': '#d4a0c8',
            'od-border': 'rgba(201, 160, 212, 0.22)',
            'od-accent-2': '#d4a574',
            'od-glass-bg': 'rgba(32, 20, 40, 0.74)',
            'od-glass-border': 'rgba(201, 160, 212, 0.28)',
            'od-glass-blur': '8px',
            'od-crt-opacity': '0.06',
            'od-tile-gap': '10px',
            'font-display': '"Arial Black", "Segoe UI", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '1.4',
            'od-icon-linecap': 'round',
            'od-icon-linejoin': 'round',
            'od-icon-fill': 'currentColor',
            'od-icon-fill-opacity': '0.88',
        },
    },
    {
        'slug': 'era-late90s',
        'name': 'Late-90s carpet den',
        'description': 'Basement rec room, disc cases, tube still in the corner.',
        'group': 'decade',
        'era': 'carpet_den_late_90s',
        'btn_primary': '#8aa4ff',
        'btn_primary_hover': '#6a88ee',
        'bg_dark_40': 'rgba(18, 16, 24, 0.9)',
        'bg_dark_30': 'rgba(10, 8, 16, 0.94)',
        'icon_pack': 'duotone',
        'tokens': {
            'od-text': '#e8ecff',
            'od-text-muted': '#9bb0ff',
            'od-border': 'rgba(138, 164, 255, 0.22)',
            'od-accent-2': '#6a8cff',
            'od-glass-bg': 'rgba(20, 16, 32, 0.76)',
            'od-glass-border': 'rgba(138, 164, 255, 0.28)',
            'od-glass-blur': '8px',
            'od-crt-opacity': '0.05',
            'od-tile-gap': '10px',
            'font-display': '"Orbitron", "Segoe UI", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '1.7',
            'od-icon-linecap': 'round',
            'od-icon-linejoin': 'round',
            'od-icon-fill': 'currentColor',
            'od-icon-fill-opacity': '0.22',
        },
    },
    {
        'slug': 'era-00s',
        'name': '2000s media centre',
        'description': 'Silver-black stand, tray-loading boxes, evening window.',
        'group': 'decade',
        'era': 'media_center_00s',
        'btn_primary': '#3f9bff',
        'btn_primary_hover': '#2b7fe0',
        'bg_dark_40': 'rgba(11, 18, 32, 0.88)',
        'bg_dark_30': 'rgba(6, 10, 20, 0.94)',
        'icon_pack': 'soft',
        'tokens': {
            'od-text': '#e8f2ff',
            'od-text-muted': '#7fd3ff',
            'od-border': 'rgba(63, 155, 255, 0.22)',
            'od-accent-2': '#7fd3ff',
            'od-glass-bg': 'rgba(10, 18, 36, 0.7)',
            'od-glass-border': 'rgba(63, 155, 255, 0.28)',
            'od-glass-blur': '10px',
            'od-crt-opacity': '0.02',
            'od-tile-gap': '11px',
            'font-display': '"Segoe UI Semibold", "Segoe UI", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '1.35',
            'od-icon-linecap': 'round',
            'od-icon-linejoin': 'round',
            'od-icon-fill': 'none',
            'od-icon-fill-opacity': '0',
        },
    },
    {
        'slug': 'era-arcade',
        'name': 'Arcade floor',
        'description': 'Dark room, marquee overhead, coins on the bezel.',
        'group': 'decade',
        'era': 'arcade_cabinet',
        'btn_primary': '#ff2d6f',
        'btn_primary_hover': '#e01858',
        'bg_dark_40': 'rgba(12, 8, 18, 0.9)',
        'bg_dark_30': 'rgba(6, 4, 12, 0.95)',
        'icon_pack': 'filled',
        'tokens': {
            'od-text': '#ffe8f0',
            'od-text-muted': '#ff8ab0',
            'od-border': 'rgba(255, 45, 111, 0.24)',
            'od-accent-2': '#25e0ff',
            'od-glass-bg': 'rgba(16, 6, 18, 0.78)',
            'od-glass-border': 'rgba(255, 45, 111, 0.32)',
            'od-glass-blur': '6px',
            'od-crt-opacity': '0.08',
            'od-tile-gap': '8px',
            'font-display': '"Arial Black", "Impact", sans-serif',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '1.5',
            'od-icon-linecap': 'round',
            'od-icon-linejoin': 'round',
            'od-icon-fill': 'currentColor',
            'od-icon-fill-opacity': '0.9',
        },
    },
    {
        'slug': 'era-desk',
        'name': 'Computer desk',
        'description': 'Home computer, desk lamp, phosphor glow.',
        'group': 'decade',
        'era': 'desk',
        'btn_primary': '#5ef08a',
        'btn_primary_hover': '#3ed46c',
        'bg_dark_40': 'rgba(13, 20, 16, 0.9)',
        'bg_dark_30': 'rgba(8, 12, 10, 0.94)',
        'icon_pack': 'outline',
        'tokens': {
            'od-text': '#e8f8ee',
            'od-text-muted': '#a9f7c1',
            'od-border': 'rgba(94, 240, 138, 0.2)',
            'od-accent-2': '#a9f7c1',
            'od-glass-bg': 'rgba(8, 20, 14, 0.82)',
            'od-glass-border': 'rgba(94, 240, 138, 0.24)',
            'od-glass-blur': '4px',
            'od-crt-opacity': '0.07',
            'od-tile-gap': '9px',
            'font-display': '"VT323", "Courier New", monospace',
            'font-ui': '"Segoe UI", "Helvetica Neue", sans-serif',
            'od-icon-stroke': '2',
            'od-icon-linecap': 'butt',
            'od-icon-linejoin': 'miter',
            'od-icon-fill': 'none',
            'od-icon-fill-opacity': '0',
        },
    },
]
