"""Per-system chrome geometry tokens for the preset themes (radii, borders,
glows, bezels) keyed by preset slug.

Split out of ``preset_themes`` in the v11 cycle (H-D.4) as a pure move.
"""



def _system_geometry(slug: str) -> dict:
    """Per-preset radius / space / type / shadow — the system visual language.

    Colour and icon stroke already live on each preset's ``tokens`` dict.
    These keys are what made packs read as tint-only: nothing overrode the
    shared scales. Slugs stay stable (preference keys); geometry is the pack.
    """
    packs = {
        'aurora': {
            'od-radius-xs': '0px',
            'od-radius-sm': '0px',
            'od-radius-md': '2px',
            'od-radius-lg': '2px',
            'od-radius-xl': '4px',
            'od-radius-2xl': '4px',
            'od-radius-3xl': '4px',
            'od-space-4': '0.5rem',
            'od-space-5': '0.65rem',
            'od-font-base': '0.95rem',
            'od-shadow-md': '0 2px 0 rgba(0, 0, 0, 0.55)',
            'od-motion-base': '80ms',
        },
        'ember': {
            'od-radius-xs': '6px',
            'od-radius-sm': '8px',
            'od-radius-md': '12px',
            'od-radius-lg': '16px',
            'od-radius-xl': '20px',
            'od-radius-2xl': '24px',
            'od-radius-3xl': '28px',
            'od-space-5': '1.05rem',
            'od-shadow-md': '0 8px 24px rgba(0, 0, 0, 0.5)',
            'od-shadow-lg': '0 18px 40px rgba(0, 0, 0, 0.55)',
        },
        'violet': {
            'od-radius-xs': '8px',
            'od-radius-sm': '10px',
            'od-radius-md': '14px',
            'od-radius-lg': '18px',
            'od-radius-xl': '22px',
            'od-radius-2xl': '28px',
            'od-radius-3xl': '32px',
            'od-space-5': '1.15rem',
            'od-shadow-md': '0 6px 20px rgba(20, 10, 40, 0.45)',
        },
        'forest': {
            'od-radius-xs': '0px',
            'od-radius-sm': '0px',
            'od-radius-md': '0px',
            'od-radius-lg': '0px',
            'od-radius-xl': '0px',
            'od-radius-2xl': '0px',
            'od-radius-3xl': '0px',
            'od-space-4': '0.45rem',
            'od-space-5': '0.7rem',
            'od-font-base': '0.92rem',
            'od-shadow-sm': 'none',
            'od-shadow-md': 'none',
            'od-motion-base': '90ms',
        },
        'ocean': {
            'od-radius-xs': '4px',
            'od-radius-sm': '6px',
            'od-radius-md': '10px',
            'od-radius-lg': '12px',
            'od-radius-xl': '14px',
            'od-radius-2xl': '18px',
            'od-radius-3xl': '22px',
            'od-space-5': '1rem',
            'od-shadow-md': '0 4px 16px rgba(0, 20, 48, 0.4)',
        },
        'rose': {
            'od-radius-xs': '6px',
            'od-radius-sm': '8px',
            'od-radius-md': '12px',
            'od-radius-lg': '14px',
            'od-radius-xl': '16px',
            'od-radius-2xl': '20px',
            'od-radius-3xl': '24px',
            'od-space-4': '0.55rem',
            'od-space-5': '0.85rem',
            'od-font-lg': '1.05rem',
        },
        'mono': {
            'od-radius-xs': '0px',
            'od-radius-sm': '0px',
            'od-radius-md': '0px',
            'od-radius-lg': '0px',
            'od-radius-xl': '0px',
            'od-radius-2xl': '0px',
            'od-radius-3xl': '0px',
            'od-space-2': '0.3rem',
            'od-space-5': '0.8rem',
            'od-shadow-sm': 'none',
            'od-shadow-md': 'none',
            'od-shadow-lg': 'none',
            'od-font-base': '0.9rem',
        },
        'sunset': {
            'od-radius-xs': '4px',
            'od-radius-sm': '8px',
            'od-radius-md': '14px',
            'od-radius-lg': '18px',
            'od-radius-xl': '22px',
            'od-radius-2xl': '26px',
            'od-radius-3xl': '30px',
            'od-font-2xl': '1.65rem',
            'od-shadow-md': '0 8px 20px rgba(40, 20, 0, 0.5)',
            'od-shadow-lg': '0 20px 44px rgba(40, 16, 0, 0.55)',
        },
        'ice': {
            'od-radius-xs': '10px',
            'od-radius-sm': '14px',
            'od-radius-md': '18px',
            'od-radius-lg': '22px',
            'od-radius-xl': '26px',
            'od-radius-2xl': '32px',
            'od-radius-3xl': '36px',
            'od-space-5': '1.2rem',
            'od-space-6': '1.75rem',
            'od-font-base': '1.05rem',
            'od-shadow-sm': '0 1px 8px rgba(120, 180, 220, 0.18)',
            'od-shadow-md': '0 8px 28px rgba(10, 30, 50, 0.35)',
        },
        'era-80s': {
            'od-radius-xs': '0px',
            'od-radius-sm': '2px',
            'od-radius-md': '2px',
            'od-radius-lg': '4px',
            'od-radius-xl': '4px',
            'od-radius-2xl': '4px',
            'od-radius-3xl': '6px',
            'od-space-4': '0.5rem',
            'od-space-5': '0.7rem',
            'od-font-base': '0.95rem',
            'od-shadow-md': '0 2px 0 rgba(0, 0, 0, 0.55)',
            'od-motion-base': '80ms',
        },
        'era-90s': {
            'od-radius-xs': '4px',
            'od-radius-sm': '6px',
            'od-radius-md': '10px',
            'od-radius-lg': '14px',
            'od-radius-xl': '18px',
            'od-radius-2xl': '22px',
            'od-radius-3xl': '26px',
            'od-space-5': '1rem',
            'od-shadow-md': '0 8px 22px rgba(40, 16, 48, 0.48)',
        },
        'era-late90s': {
            'od-radius-xs': '3px',
            'od-radius-sm': '6px',
            'od-radius-md': '10px',
            'od-radius-lg': '12px',
            'od-radius-xl': '16px',
            'od-radius-2xl': '20px',
            'od-radius-3xl': '24px',
            'od-shadow-md': '0 6px 18px rgba(16, 12, 32, 0.5)',
        },
        'era-00s': {
            'od-radius-xs': '6px',
            'od-radius-sm': '8px',
            'od-radius-md': '12px',
            'od-radius-lg': '16px',
            'od-radius-xl': '20px',
            'od-radius-2xl': '24px',
            'od-radius-3xl': '28px',
            'od-space-5': '1.05rem',
            'od-shadow-md': '0 6px 20px rgba(8, 20, 40, 0.42)',
        },
        'era-arcade': {
            'od-radius-xs': '2px',
            'od-radius-sm': '4px',
            'od-radius-md': '8px',
            'od-radius-lg': '12px',
            'od-radius-xl': '16px',
            'od-radius-2xl': '20px',
            'od-radius-3xl': '24px',
            'od-space-4': '0.5rem',
            'od-shadow-md': '0 8px 24px rgba(40, 0, 20, 0.55)',
            'od-shadow-lg': '0 18px 40px rgba(40, 0, 24, 0.6)',
        },
        'era-desk': {
            'od-radius-xs': '0px',
            'od-radius-sm': '0px',
            'od-radius-md': '0px',
            'od-radius-lg': '0px',
            'od-radius-xl': '0px',
            'od-radius-2xl': '0px',
            'od-radius-3xl': '0px',
            'od-space-4': '0.45rem',
            'od-space-5': '0.7rem',
            'od-font-base': '0.92rem',
            'od-shadow-sm': 'none',
            'od-shadow-md': 'none',
            'od-motion-base': '90ms',
        },
        # E1 console-family packs (v11 cycle, H-T).
        'console-cartridge': {
            'od-radius-xs': '0px',
            'od-radius-sm': '2px',
            'od-radius-md': '3px',
            'od-radius-lg': '4px',
            'od-radius-xl': '4px',
            'od-radius-2xl': '6px',
            'od-radius-3xl': '6px',
            'od-space-4': '0.5rem',
            'od-font-base': '0.92rem',
            'od-shadow-sm': 'none',
            'od-shadow-md': '0 4px 0 rgba(0, 0, 0, 0.6)',
            'od-motion-base': '100ms',
        },
        'console-disc': {
            'od-radius-xs': '6px',
            'od-radius-sm': '10px',
            'od-radius-md': '14px',
            'od-radius-lg': '18px',
            'od-radius-xl': '22px',
            'od-radius-2xl': '26px',
            'od-radius-3xl': '32px',
            'od-font-base': '0.98rem',
            'od-shadow-md': '0 8px 22px rgba(0, 40, 90, 0.45)',
            'od-shadow-lg': '0 18px 40px rgba(0, 30, 70, 0.5)',
        },
        'console-signal': {
            'od-radius-xs': '4px',
            'od-radius-sm': '8px',
            'od-radius-md': '12px',
            'od-radius-lg': '16px',
            'od-radius-xl': '20px',
            'od-radius-2xl': '24px',
            'od-radius-3xl': '28px',
            'od-font-base': '1rem',
            'od-shadow-sm': '0 1px 6px rgba(61, 219, 122, 0.12)',
            'od-shadow-md': '0 8px 24px rgba(0, 0, 0, 0.55)',
            'od-motion-base': '160ms',
        },
        'console-deepblue': {
            'od-radius-xs': '0px',
            'od-radius-sm': '2px',
            'od-radius-md': '4px',
            'od-radius-lg': '6px',
            'od-radius-xl': '6px',
            'od-radius-2xl': '8px',
            'od-radius-3xl': '8px',
            'od-space-5': '0.85rem',
            'od-font-2xl': '1.7rem',
            'od-shadow-md': '6px 6px 0 rgba(0, 0, 0, 0.5)',
            'od-motion-base': '110ms',
        },
        'console-woodgrain': {
            'od-radius-xs': '2px',
            'od-radius-sm': '4px',
            'od-radius-md': '6px',
            'od-radius-lg': '8px',
            'od-radius-xl': '10px',
            'od-radius-2xl': '12px',
            'od-radius-3xl': '14px',
            'od-space-4': '0.55rem',
            'od-font-base': '0.94rem',
            'od-shadow-md': '0 6px 14px rgba(40, 20, 0, 0.55)',
            'od-motion-base': '130ms',
        },
        'console-terminal': {
            'od-radius-xs': '0px',
            'od-radius-sm': '0px',
            'od-radius-md': '0px',
            'od-radius-lg': '0px',
            'od-radius-xl': '0px',
            'od-radius-2xl': '0px',
            'od-radius-3xl': '0px',
            'od-space-4': '0.45rem',
            'od-space-5': '0.7rem',
            'od-font-base': '0.92rem',
            'od-shadow-sm': 'none',
            'od-shadow-md': 'none',
            'od-motion-base': '80ms',
        },
    }
    return packs.get(slug, {})
