#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for Oneirodex (Flask + React, PostgreSQL 17).
# Runs after the repository is checked out. Safe to run repeatedly.
set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

PG_VERSION=17

echo "==> Ensuring system packages (PostgreSQL ${PG_VERSION}, Python venv, build deps)"
if ! command -v "/usr/lib/postgresql/${PG_VERSION}/bin/postgres" >/dev/null 2>&1; then
  # PGDG repo for PostgreSQL 17 on Ubuntu (matches README "PostgreSQL 17+").
  sudo apt-get install -y curl ca-certificates gnupg
  sudo install -d /usr/share/postgresql-common/pgdg
  sudo curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc \
    -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
  . /etc/os-release
  echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt ${VERSION_CODENAME}-pgdg main" \
    | sudo tee /etc/apt/sources.list.d/pgdg.list >/dev/null
  sudo apt-get update
  sudo apt-get install -y "postgresql-${PG_VERSION}" "postgresql-client-${PG_VERSION}"
fi

# Python venv + native build headers for psycopg2/argon2/cffi, plus the archive
# backends (bsdtar / 7z) the app uses to extract .rar/.7z ROMs — parity with the
# runtime Dockerfile (libarchive-tools + p7zip-full).
sudo apt-get install -y python3.12-venv python3-dev build-essential libpq-dev \
  libarchive-tools p7zip-full

echo "==> Starting PostgreSQL cluster"
sudo pg_ctlcluster "${PG_VERSION}" main start || true
# Wait for the socket to accept connections.
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done

echo "==> Ensuring postgres role password and databases"
sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='oneirodex'" | grep -q 1 \
  || sudo -u postgres createdb oneirodex
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='oneirodextest'" | grep -q 1 \
  || sudo -u postgres createdb oneirodextest

echo "==> Creating local data folders"
mkdir -p "${REPO_ROOT}/data/games" "${REPO_ROOT}/data/library"

echo "==> Writing .env (only if missing so a generated SECRET_KEY stays stable)"
if [ ! -f "${REPO_ROOT}/.env" ]; then
  SECRET="$(python3 -c 'import secrets; print(secrets.token_urlsafe(64))')"
  cat > "${REPO_ROOT}/.env" <<EOF
# Cloud Agent dev environment (native, non-Docker) — generated by .cursor/install.sh
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/oneirodex
TEST_DATABASE_URL=postgresql://postgres:postgres@localhost:5432/oneirodextest
SECRET_KEY=${SECRET}
DATA_FOLDER_GAMES=${REPO_ROOT}/data/games
BASE_FOLDER_POSIX=${REPO_ROOT}/data/games
UPLOAD_FOLDER=${REPO_ROOT}/oneirodex/static/library
ONEIRODEX_LIBRARY_ROOTS=
LIBRARY_HOST_PATH=${REPO_ROOT}/data/library
DEV_MODE=false
PORT=5006
UVICORN_WORKERS=1
ONEIRODEX_ENABLE_BACKGROUND_WORKERS=true
ONEIRODEX_LOG_LEVEL=INFO
SESSION_COOKIE_SECURE=false
REMEMBER_COOKIE_SECURE=false
OIDC_ENABLED=false
EOF
fi

echo "==> Python virtualenv + dependencies"
if [ ! -x "${REPO_ROOT}/venv/bin/python" ]; then
  python3 -m venv "${REPO_ROOT}/venv"
fi
# shellcheck disable=SC1091
source "${REPO_ROOT}/venv/bin/activate"
python -m pip install --upgrade pip
pip install -r requirements-dev.txt

echo "==> Frontend dependencies + SPA builds"
npm ci
# api-client is a workspace dependency of the SPAs; build it first. member-app,
# admin-app, and ops-glance are the three bundles the runtime Dockerfile ships to
# oneirodex/static/dist/ and the Flask app serves.
npm run build --workspace frontend/api-client
npm run build --workspace frontend/member-app
npm run build --workspace frontend/admin-app
npm run build --workspace frontend/ops-glance

echo "==> Install complete"
