"""baseline schema (squash of updateschema.py)

Revision ID: b9ab856b09ff
Revises: 
Create Date: 2026-09-09 05:22:10.240283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ab856b09ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_file_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('discovery_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('section_type', sa.String(length=20), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('layout', sa.String(length=20), nullable=False),
    sa.Column('pin_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_pattern', sa.String(), nullable=True),
    sa.Column('case_sensitive', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('free_game_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('claim_url', sa.String(length=1024), nullable=True),
    sa.Column('store_url', sa.String(length=1024), nullable=True),
    sa.Column('worth', sa.String(length=64), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store', 'external_id', name='uq_free_game_offer_store_ext')
    )
    op.create_index(op.f('ix_free_game_offers_active'), 'free_game_offers', ['active'], unique=False)
    op.create_index(op.f('ix_free_game_offers_source'), 'free_game_offers', ['source'], unique=False)
    op.create_index(op.f('ix_free_game_offers_store'), 'free_game_offers', ['store'], unique=False)
    op.create_table('game_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('smtp_server', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=True),
    sa.Column('smtp_default_sender', sa.String(length=255), nullable=True),
    sa.Column('smtp_last_tested', sa.DateTime(), nullable=True),
    sa.Column('smtp_enabled', sa.Boolean(), nullable=True),
    sa.Column('enable_delete_game_on_disk', sa.Boolean(), nullable=True),
    sa.Column('igdb_client_id', sa.String(length=255), nullable=True),
    sa.Column('igdb_client_secret', sa.String(length=255), nullable=True),
    sa.Column('igdb_last_tested', sa.DateTime(), nullable=True),
    sa.Column('enable_game_updates', sa.Boolean(), nullable=True),
    sa.Column('update_folder_name', sa.String(length=255), nullable=True),
    sa.Column('enable_game_extras', sa.Boolean(), nullable=True),
    sa.Column('extras_folder_name', sa.String(length=255), nullable=True),
    sa.Column('site_url', sa.String(length=255), nullable=True),
    sa.Column('use_turbo_image_downloads', sa.Boolean(), nullable=True),
    sa.Column('turbo_download_threads', sa.Integer(), nullable=True),
    sa.Column('turbo_download_batch_size', sa.Integer(), nullable=True),
    sa.Column('scan_thread_count', sa.Integer(), nullable=True),
    sa.Column('setup_in_progress', sa.Boolean(), nullable=True),
    sa.Column('setup_current_step', sa.Integer(), nullable=True),
    sa.Column('setup_completed', sa.Boolean(), nullable=True),
    sa.Column('attract_mode_enabled', sa.Boolean(), nullable=True),
    sa.Column('attract_mode_idle_timeout', sa.Integer(), nullable=True),
    sa.Column('attract_mode_settings', sa.Text(), nullable=True),
    sa.Column('enable_hltb_integration', sa.Boolean(), nullable=True),
    sa.Column('hltb_rate_limit_delay', sa.Float(), nullable=True),
    sa.Column('use_local_metadata', sa.Boolean(), nullable=True),
    sa.Column('write_local_metadata', sa.Boolean(), nullable=True),
    sa.Column('use_local_images', sa.Boolean(), nullable=True),
    sa.Column('local_metadata_filename', sa.String(length=50), nullable=True),
    sa.Column('propose_only_scan', sa.Boolean(), nullable=True),
    sa.Column('oidc_enabled', sa.Boolean(), nullable=True),
    sa.Column('oidc_issuer_url', sa.String(length=512), nullable=True),
    sa.Column('oidc_client_id', sa.String(length=255), nullable=True),
    sa.Column('oidc_client_secret', sa.String(length=512), nullable=True),
    sa.Column('oidc_redirect_uri', sa.String(length=512), nullable=True),
    sa.Column('oidc_scopes', sa.String(length=255), nullable=True),
    sa.Column('oidc_role_claim', sa.String(length=64), nullable=True),
    sa.Column('oidc_role_map', sa.Text(), nullable=True),
    sa.Column('oidc_display_name', sa.String(length=120), nullable=True),
    sa.Column('enable_store_ownership_sync', sa.Boolean(), nullable=True),
    sa.Column('steam_web_api_key', sa.String(length=255), nullable=True),
    sa.Column('steamgriddb_api_key', sa.String(length=255), nullable=True),
    sa.Column('emulator_profiles', sa.Text(), nullable=True),
    sa.Column('enable_arr_module', sa.Boolean(), nullable=True),
    sa.Column('arr_settings', sa.Text(), nullable=True),
    sa.Column('enable_emulator_save_sync', sa.Boolean(), nullable=True),
    sa.Column('allow_children_in_household_lobby', sa.Boolean(), nullable=True),
    sa.Column('encrypt_emulator_saves', sa.Boolean(), nullable=True),
    sa.Column('giantbomb_api_key', sa.String(length=255), nullable=True),
    sa.Column('mobygames_api_key', sa.String(length=255), nullable=True),
    sa.Column('thegamesdb_api_key', sa.String(length=255), nullable=True),
    sa.Column('quality_profiles', sa.Text(), nullable=True),
    sa.Column('detail_layout', sa.Text(), nullable=True),
    sa.Column('enable_ai_assist', sa.Boolean(), nullable=True),
    sa.Column('enable_malware_scan', sa.Boolean(), nullable=True),
    sa.Column('ollama_base_url', sa.String(length=512), nullable=True),
    sa.Column('ollama_model', sa.String(length=120), nullable=True),
    sa.Column('community_chat_url', sa.String(length=512), nullable=True),
    sa.Column('community_chat_label', sa.String(length=120), nullable=True),
    sa.Column('admin_notify_new_games', sa.Boolean(), nullable=True),
    sa.Column('admin_notify_game_updates', sa.Boolean(), nullable=True),
    sa.Column('admin_notify_game_extras', sa.Boolean(), nullable=True),
    sa.Column('admin_notify_downloads', sa.Boolean(), nullable=True),
    sa.Column('admin_notify_support', sa.Boolean(), nullable=True),
    sa.Column('enable_remote_play', sa.Boolean(), nullable=True),
    sa.Column('remote_play_settings', sa.Text(), nullable=True),
    sa.Column('loading_icon_mode', sa.String(length=16), nullable=True),
    sa.Column('loading_icon_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('global_settings_singleton', 'global_settings', [sa.literal_column('(true)')], unique=True)
    op.create_table('igdb_platform_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_platform', sa.String(length=32), nullable=False),
    sa.Column('igdb_game_id', sa.Integer(), nullable=False),
    sa.Column('igdb_platform_id', sa.Integer(), nullable=True),
    sa.Column('region_code', sa.String(length=16), nullable=False),
    sa.Column('igdb_region', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_platform', 'igdb_game_id', 'region_code', name='uq_igdb_platform_release')
    )
    op.create_index(op.f('ix_igdb_platform_releases_igdb_game_id'), 'igdb_platform_releases', ['igdb_game_id'], unique=False)
    op.create_index(op.f('ix_igdb_platform_releases_library_platform'), 'igdb_platform_releases', ['library_platform'], unique=False)
    op.create_index('ix_igdb_platform_releases_platform_region', 'igdb_platform_releases', ['library_platform', 'region_code'], unique=False)
    op.create_table('ignored_file_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('libraries',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.Enum('OTHER', 'PCWIN', 'PCDOS', 'MAC', 'NES', 'SNES', 'NGC', 'N64', 'GB', 'GBA', 'GBC', 'NDS', 'VB', 'WII', 'N3DS', 'SEGA_MD', 'SEGA_MS', 'SEGA_CD', 'SEGA_32X', 'SEGA_GG', 'SEGA_SATURN', 'SEGA_DC', 'ATARI_7800', 'ATARI_5200', 'ATARI_2600', 'LYNX', 'JAGUAR', 'PCE', 'PCFX', 'NGP', 'WS', 'COLECO', 'THREEDO', 'VECTREX', 'VICE_X64SC', 'VICE_X128', 'VICE_XVIC', 'VICE_XPLUS4', 'VICE_XPET', 'XBOX', 'X360', 'XONE', 'XSX', 'PSX', 'PS2', 'PS3', 'PS4', 'PS5', 'PSP', 'PSVITA', 'INTV', 'CHAF', 'O2EM', 'NEOGEO_CD', 'NEOGEO', 'SWITCH', 'ARCADE', 'AMIGA', 'SEGA_SG1000', 'SUPERGRAFX', 'PCE_CD', 'NGPC', 'SUPERVISION', 'GX4000', 'ASTROCADE', 'ARCADIA', 'CREATIVISION', 'ADVISION', 'STUDIO2', 'ACTIONMAX', 'DAPHNE', 'PINBALL', 'WII_U', 'POKE_MINI', 'GAME_WATCH', 'CD_I', 'SEGA_PICO', 'JAGUAR_CD', 'AMIGA_CD32', 'MSX', 'ZX_SPECTRUM', 'CPC', 'ATARI_ST', 'APPLE_II', 'ATARI_8BIT', 'X68000', 'PC_98', 'BBC_MICRO', name='libraryplatform'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('scan_depth', sa.Integer(), nullable=False),
    sa.Column('last_scan_folder', sa.String(length=512), nullable=True),
    sa.Column('watch_enabled', sa.Boolean(), nullable=True),
    sa.Column('group_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_libraries_group_name'), 'libraries', ['group_name'], unique=False)
    op.create_table('multiplayer_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('player_perspectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('about', sa.String(length=256), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('lastlogin', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('avatarpath', sa.String(length=256), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(length=256), nullable=True),
    sa.Column('password_reset_token', sa.String(length=256), nullable=True),
    sa.Column('token_creation_time', sa.DateTime(), nullable=True),
    sa.Column('invite_quota', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('about'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_prefix'), 'api_tokens', ['token_prefix'], unique=False)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('chat_spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('is_child_safe', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('client_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('device_kind', sa.String(length=16), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('client_version', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_client_devices_user_device')
    )
    op.create_index(op.f('ix_client_devices_user_id'), 'client_devices', ['user_id'], unique=False)
    op.create_table('custom_emoji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=80), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('detail_layout_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('layout', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_detail_preset_user_name')
    )
    op.create_index(op.f('ix_detail_layout_presets_user_id'), 'detail_layout_presets', ['user_id'], unique=False)
    op.create_table('duplicate_fix_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unmatched_folder_id', sa.String(length=36), nullable=True),
    sa.Column('folder_path', sa.String(length=1024), nullable=False),
    sa.Column('matched_game_uuid', sa.String(length=36), nullable=True),
    sa.Column('match_reason', sa.String(length=64), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_fix_logs_matched_game_uuid'), 'duplicate_fix_logs', ['matched_game_uuid'], unique=False)
    op.create_index(op.f('ix_duplicate_fix_logs_unmatched_folder_id'), 'duplicate_fix_logs', ['unmatched_folder_id'], unique=False)
    op.create_table('game_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('igdb_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('storyline', sa.Text(), nullable=True),
    sa.Column('aggregated_rating', sa.Float(), nullable=True),
    sa.Column('aggregated_rating_count', sa.Integer(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('first_release_date', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('RELEASED', 'ALPHA', 'BETA', 'EARLY_ACCESS', 'OFFLINE', 'CANCELLED', name='status'), nullable=True),
    sa.Column('category', sa.Enum('MAIN_GAME', 'DLC_ADDON', 'EXPANSION', 'BUNDLE', 'STANDALONE_EXPANSION', 'MOD', 'EPISODE', 'SEASON', 'REMAKE', 'REMASTER', 'EXPANDED_GAME', 'PORT', 'PACK', 'UPDATE', name='category'), nullable=True),
    sa.Column('total_rating', sa.Float(), nullable=True),
    sa.Column('total_rating_count', sa.Integer(), nullable=True),
    sa.Column('url_igdb', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('video_urls', sa.String(), nullable=True),
    sa.Column('full_disk_path', sa.String(), nullable=True),
    sa.Column('path_status', sa.String(length=16), nullable=True),
    sa.Column('file_crc', sa.String(length=16), nullable=True),
    sa.Column('file_md5', sa.String(length=32), nullable=True),
    sa.Column('file_sha1', sa.String(length=40), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_identified', sa.DateTime(), nullable=True),
    sa.Column('steam_url', sa.String(), nullable=True),
    sa.Column('times_downloaded', sa.Integer(), nullable=True),
    sa.Column('nfo_content', sa.Text(), nullable=True),
    sa.Column('hltb_id', sa.Integer(), nullable=True),
    sa.Column('hltb_main_story', sa.Float(), nullable=True),
    sa.Column('hltb_main_extra', sa.Float(), nullable=True),
    sa.Column('hltb_completionist', sa.Float(), nullable=True),
    sa.Column('hltb_all_styles', sa.Float(), nullable=True),
    sa.Column('hltb_last_updated', sa.DateTime(), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('library_uuid', sa.String(length=36), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('steam_app_id', sa.Integer(), nullable=True),
    sa.Column('local_version', sa.String(length=100), nullable=True),
    sa.Column('remote_version_summary', sa.String(length=255), nullable=True),
    sa.Column('freshness_status', sa.String(length=32), nullable=True),
    sa.Column('freshness_confidence', sa.String(length=16), nullable=True),
    sa.Column('freshness_checked_at', sa.DateTime(), nullable=True),
    sa.Column('freshness_payload', sa.JSON(), nullable=True),
    sa.Column('rom_region', sa.String(length=16), nullable=True),
    sa.Column('rom_languages', sa.String(length=64), nullable=True),
    sa.Column('has_english', sa.Boolean(), nullable=True),
    sa.Column('disc_index', sa.Integer(), nullable=True),
    sa.Column('disc_count', sa.Integer(), nullable=True),
    sa.Column('store_specs', sa.JSON(), nullable=True),
    sa.Column('item_kind', sa.String(length=16), server_default='game', nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.ForeignKeyConstraint(['library_uuid'], ['libraries.uuid'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('igdb_id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_games_file_crc'), 'games', ['file_crc'], unique=False)
    op.create_index(op.f('ix_games_file_md5'), 'games', ['file_md5'], unique=False)
    op.create_index(op.f('ix_games_file_sha1'), 'games', ['file_sha1'], unique=False)
    op.create_table('invite_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('creator_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('recipient_email', sa.String(length=120), nullable=True),
    sa.Column('used_by', sa.String(length=36), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sent_date', sa.DateTime(), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_platform', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_platform', 'region', name='uq_reference_set_platform_region')
    )
    op.create_index(op.f('ix_reference_sets_library_platform'), 'reference_sets', ['library_platform'], unique=False)
    op.create_index(op.f('ix_reference_sets_region'), 'reference_sets', ['region'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('folders', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('Games', name='content_type_enum'), nullable=True),
    sa.Column('schedule', sa.Enum('8_hours', '24_hours', '48_hours', name='schedule_enum'), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('Scheduled', 'Queued', 'Running', 'Stopping', 'Completed', 'Failed', 'Cancelled', name='status_enum'), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_folders', sa.Integer(), nullable=True),
    sa.Column('folders_success', sa.Integer(), nullable=True),
    sa.Column('folders_failed', sa.Integer(), nullable=True),
    sa.Column('library_uuid', sa.String(length=36), nullable=True),
    sa.Column('removed_count', sa.Integer(), nullable=True),
    sa.Column('scan_folder', sa.String(length=512), nullable=True),
    sa.Column('setting_remove', sa.Boolean(), nullable=True),
    sa.Column('setting_filefolder', sa.Boolean(), nullable=True),
    sa.Column('setting_download_missing_images', sa.Boolean(), nullable=True),
    sa.Column('setting_force_updates_extras', sa.Boolean(), nullable=True),
    sa.Column('current_processing', sa.String(length=255), nullable=True),
    sa.Column('last_progress_update', sa.DateTime(), nullable=True),
    sa.Column('owner_token', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['library_uuid'], ['libraries.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=16), nullable=False),
    sa.Column('external_account_id', sa.String(length=64), nullable=True),
    sa.Column('credential', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'store', name='uq_store_account_user_store')
    )
    op.create_index(op.f('ix_store_accounts_user_id'), 'store_accounts', ['user_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('area', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('role_at_submit', sa.String(length=32), nullable=True),
    sa.Column('deploy_hint', sa.String(length=64), nullable=True),
    sa.Column('client_hint', sa.String(length=120), nullable=True),
    sa.Column('url_hint', sa.String(length=512), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_issue_url', sa.String(length=512), nullable=True),
    sa.Column('github_sync', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=True),
    sa.Column('event_text', sa.String(length=256), nullable=False),
    sa.Column('event_level', sa.String(length=32), nullable=True),
    sa.Column('audit_user', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_attract_mode_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('has_customized', sa.Boolean(), nullable=True),
    sa.Column('filter_settings', sa.Text(), nullable=True),
    sa.Column('autoplay_settings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_content_filters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'filter_type', 'name')
    )
    op.create_table('user_friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['friend_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_user_id', name='uq_user_friendship')
    )
    op.create_index(op.f('ix_user_friendships_friend_user_id'), 'user_friendships', ['friend_user_id'], unique=False)
    op.create_index(op.f('ix_user_friendships_user_id'), 'user_friendships', ['user_id'], unique=False)
    op.create_table('user_library_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['library_uuid'], ['libraries.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'library_uuid')
    )
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('items_per_page', sa.Integer(), server_default='50', nullable=True),
    sa.Column('default_sort', sa.String(length=50), nullable=True),
    sa.Column('default_sort_order', sa.String(length=4), nullable=True),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('icon_pack', sa.String(length=50), nullable=True),
    sa.Column('font', sa.String(length=64), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('preferred_game_locale', sa.String(length=16), nullable=False),
    sa.Column('tile_size', sa.String(length=8), nullable=False),
    sa.Column('show_tile_titles', sa.Boolean(), nullable=False),
    sa.Column('notify_friend_requests', sa.Boolean(), nullable=False),
    sa.Column('notify_activity', sa.Boolean(), nullable=False),
    sa.Column('notify_mentions', sa.Boolean(), nullable=False),
    sa.Column('notify_chat', sa.Boolean(), nullable=False),
    sa.Column('notify_support', sa.Boolean(), nullable=False),
    sa.Column('notify_free_games', sa.Boolean(), nullable=False),
    sa.Column('share_activity', sa.Boolean(), nullable=False),
    sa.Column('discover_pins', sa.Text(), nullable=True),
    sa.Column('discover_hidden', sa.Text(), nullable=True),
    sa.Column('email_notify_social', sa.Boolean(), nullable=False),
    sa.Column('email_digest_daily', sa.Boolean(), nullable=False),
    sa.Column('email_digest_last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('detail_layout', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_taste_facets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('facet_type', sa.String(length=16), nullable=False),
    sa.Column('facet_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'facet_type', 'facet_id', name='uq_user_taste_facet')
    )
    op.create_index(op.f('ix_user_taste_facets_user_id'), 'user_taste_facets', ['user_id'], unique=False)
    op.create_table('chat_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_child_safe', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['space_id'], ['chat_spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_chat_channels_space_id'), 'chat_channels', ['space_id'], unique=False)
    op.create_table('chat_space_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['space_id'], ['chat_spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_space_invites_space_id'), 'chat_space_invites', ['space_id'], unique=False)
    op.create_index(op.f('ix_chat_space_invites_token'), 'chat_space_invites', ['token'], unique=True)
    op.create_table('chat_space_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['chat_spaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_id', 'user_id', name='uq_chat_space_member')
    )
    op.create_index(op.f('ix_chat_space_members_space_id'), 'chat_space_members', ['space_id'], unique=False)
    op.create_index(op.f('ix_chat_space_members_user_id'), 'chat_space_members', ['user_id'], unique=False)
    op.create_table('download_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('zip_file_path', sa.String(), nullable=True),
    sa.Column('request_time', sa.DateTime(), nullable=True),
    sa.Column('completion_time', sa.DateTime(), nullable=True),
    sa.Column('download_size', sa.Float(), nullable=False),
    sa.Column('file_location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emulator_saves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('slot_name', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_uuid', 'slot_name', name='uq_emulator_save_slot')
    )
    op.create_index(op.f('ix_emulator_saves_game_uuid'), 'emulator_saves', ['game_uuid'], unique=False)
    op.create_index(op.f('ix_emulator_saves_user_id'), 'emulator_saves', ['user_id'], unique=False)
    op.create_table('game_collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['game_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'game_uuid', name='uq_collection_game')
    )
    op.create_table('game_developer_association',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'developer_id')
    )
    op.create_table('game_extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('times_downloaded', sa.Integer(), nullable=True),
    sa.Column('nfo_content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('extra_kind', sa.String(length=32), nullable=True),
    sa.Column('patch_format', sa.String(length=8), nullable=True),
    sa.Column('target_language', sa.String(length=16), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('disc_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('game_game_mode_association',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_mode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['game_mode_id'], ['game_modes.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'game_mode_id')
    )
    op.create_table('game_genre_association',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'genre_id')
    )
    op.create_table('game_multiplayer_mode_association',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('multiplayer_mode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['multiplayer_mode_id'], ['multiplayer_modes.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'multiplayer_mode_id')
    )
    op.create_table('game_platform_association',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'platform_id')
    )
    op.create_table('game_player_perspective_association',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_perspective_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_perspective_id'], ['player_perspectives.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_perspective_id')
    )
    op.create_table('game_related_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('media_kind', sa.String(length=16), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('creator', sa.String(length=160), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_related_media_game_uuid'), 'game_related_media', ['game_uuid'], unique=False)
    op.create_table('game_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('linked_game_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['linked_game_uuid'], ['games.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_requests_user_id'), 'game_requests', ['user_id'], unique=False)
    op.create_table('game_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('connect_string', sa.String(length=512), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=True),
    sa.Column('health_url', sa.String(length=512), nullable=True),
    sa.Column('compose_project', sa.String(length=128), nullable=True),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('invite_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_game_servers_game_uuid'), 'game_servers', ['game_uuid'], unique=False)
    op.create_table('game_similarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('neighbour_uuid', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['neighbour_uuid'], ['games.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_uuid', 'neighbour_uuid', 'method', name='uq_game_similarity')
    )
    op.create_index(op.f('ix_game_similarity_game_uuid'), 'game_similarity', ['game_uuid'], unique=False)
    op.create_index(op.f('ix_game_similarity_neighbour_uuid'), 'game_similarity', ['neighbour_uuid'], unique=False)
    op.create_table('game_theme_association',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'theme_id')
    )
    op.create_table('game_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('times_downloaded', sa.Integer(), nullable=True),
    sa.Column('nfo_content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('game_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('url_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('image_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('igdb_image_id', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('is_downloaded', sa.Boolean(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('generated_by', sa.String(length=32), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pc_cheats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('single_player_only', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pc_cheats_game_uuid'), 'pc_cheats', ['game_uuid'], unique=False)
    op.create_table('play_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_sessions_game_uuid'), 'play_sessions', ['game_uuid'], unique=False)
    op.create_index(op.f('ix_play_sessions_user_id'), 'play_sessions', ['user_id'], unique=False)
    op.create_table('reference_set_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('normalized_name', sa.String(length=512), nullable=False),
    sa.Column('crc', sa.String(length=16), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('sha1', sa.String(length=40), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('serial', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['reference_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_set_entries_set_id'), 'reference_set_entries', ['set_id'], unique=False)
    op.create_index('ix_reference_set_entries_set_norm', 'reference_set_entries', ['set_id', 'normalized_name'], unique=False)
    op.create_table('unmatched_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('library_uuid', sa.String(length=36), nullable=True),
    sa.Column('scan_job_id', sa.String(length=36), nullable=True),
    sa.Column('folder_path', sa.String(), nullable=True),
    sa.Column('failed_time', sa.DateTime(), nullable=True),
    sa.Column('content_type', sa.Enum('Games', name='unmatched_folder_content_type_enum'), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Ignore', 'Duplicate', 'Unmatched', name='unmatched_folder_status_enum'), nullable=True),
    sa.Column('matched_game_uuid', sa.String(length=36), nullable=True),
    sa.Column('match_reason', sa.String(length=64), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('suggested_kind', sa.String(length=16), nullable=True),
    sa.Column('suggested_candidate_name', sa.String(length=255), nullable=True),
    sa.Column('stage_e_candidates', sa.JSON(), nullable=True),
    sa.Column('stage_e', sa.JSON(), nullable=True),
    sa.Column('search_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('bad_match_reason', sa.String(length=32), nullable=True),
    sa.Column('bad_match_note', sa.String(length=500), nullable=True),
    sa.Column('bad_match_at', sa.DateTime(), nullable=True),
    sa.Column('bad_match_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bad_match_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_uuid'], ['libraries.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unmatched_folders_matched_game_uuid'), 'unmatched_folders', ['matched_game_uuid'], unique=False)
    op.create_table('user_discover_impressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('shown_count', sa.Integer(), nullable=False),
    sa.Column('last_shown_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_uuid', name='uq_user_discover_impression')
    )
    op.create_index(op.f('ix_user_discover_impressions_game_uuid'), 'user_discover_impressions', ['game_uuid'], unique=False)
    op.create_index(op.f('ix_user_discover_impressions_user_id'), 'user_discover_impressions', ['user_id'], unique=False)
    op.create_table('user_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_uuid')
    )
    op.create_table('user_game_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('total_seconds', sa.Integer(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_uuid', name='uq_user_game_progress')
    )
    op.create_index(op.f('ix_user_game_progress_game_uuid'), 'user_game_progress', ['game_uuid'], unique=False)
    op.create_index(op.f('ix_user_game_progress_user_id'), 'user_game_progress', ['user_id'], unique=False)
    op.create_table('user_game_status',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_uuid'], ['games.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_uuid')
    )
    op.create_table('user_owned_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=16), nullable=False),
    sa.Column('external_app_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('matched_game_uuid', sa.String(length=36), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matched_game_uuid'], ['games.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'store', 'external_app_id', name='uq_user_owned_title')
    )
    op.create_index(op.f('ix_user_owned_titles_matched_game_uuid'), 'user_owned_titles', ['matched_game_uuid'], unique=False)
    op.create_index(op.f('ix_user_owned_titles_user_id'), 'user_owned_titles', ['user_id'], unique=False)
    op.create_table('chat_channel_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'user_id', name='uq_chat_channel_member')
    )
    op.create_index(op.f('ix_chat_channel_members_channel_id'), 'chat_channel_members', ['channel_id'], unique=False)
    op.create_index(op.f('ix_chat_channel_members_user_id'), 'chat_channel_members', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_channel_id'), 'chat_messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_parent_message_id'), 'chat_messages', ['parent_message_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('chat_message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=120), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_attachments_channel_id'), 'chat_message_attachments', ['channel_id'], unique=False)
    op.create_index(op.f('ix_chat_message_attachments_message_id'), 'chat_message_attachments', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_message_attachments_uploaded_by_user_id'), 'chat_message_attachments', ['uploaded_by_user_id'], unique=False)
    op.create_table('chat_message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_chat_message_reaction')
    )
    op.create_index(op.f('ix_chat_message_reactions_message_id'), 'chat_message_reactions', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_message_reactions_user_id'), 'chat_message_reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # --- squashed from oneirodex/updateschema.py -------------------------------
    # Objects the raw-DDL pass created that are NOT declared on
    # oneirodex/models.py metadata. Kept here so `alembic upgrade head` on a
    # fresh database reproduces the full production schema (perf indexes plus
    # the partial-unique "one primary artwork per game" constraints). These are
    # the entries catalogued in docs/dev/alembic-baseline-notes.md as the known
    # `alembic check` delta.
    op.create_index(
        'idx_user_game_status_lookup', 'user_game_status',
        ['user_id', 'game_uuid'], unique=False,
    )
    op.create_index('ix_client_devices_last_seen_at', 'client_devices', ['last_seen_at'], unique=False)
    op.create_index('ix_duplicate_fix_logs_created_at', 'duplicate_fix_logs', [sa.text('created_at DESC')], unique=False)
    op.create_index('ix_duplicate_fix_logs_matched_game', 'duplicate_fix_logs', ['matched_game_uuid'], unique=False)
    op.create_index('ix_games_library_uuid', 'games', ['library_uuid'], unique=False)
    op.create_index('ix_games_name', 'games', ['name'], unique=False)
    op.create_index('ix_games_date_created', 'games', [sa.text('date_created DESC')], unique=False)
    op.create_index('ix_games_rating', 'games', ['rating'], unique=False)
    op.create_index('ix_games_item_kind', 'games', ['item_kind'], unique=False)
    op.create_index('ix_games_path_status', 'games', ['path_status'], unique=False)
    op.create_index('ix_user_content_filters_user_id', 'user_content_filters', ['user_id'], unique=False)
    op.create_index('ix_user_library_access_user_id', 'user_library_access', ['user_id'], unique=False)
    op.create_index('ix_user_library_access_library_uuid', 'user_library_access', ['library_uuid'], unique=False)
    for _kind in ('cover', 'box', 'cart', 'disc', 'logo', 'hero', 'fanart'):
        op.create_index(
            f'unique_game_{_kind}_image', 'images', ['game_uuid'], unique=True,
            postgresql_where=sa.text(f"image_type = '{_kind}'"),
        )

    # Cheap real diff: updateschema set this server-side default; models.py now
    # declares it too (server_default='50'), so it is inside the baseline here.
    op.alter_column('user_preferences', 'items_per_page', server_default='50')


def downgrade() -> None:
    """Downgrade schema."""
    # --- squashed-from-updateschema objects (see upgrade) ---
    op.alter_column('user_preferences', 'items_per_page', server_default=None)
    for _kind in ('cover', 'box', 'cart', 'disc', 'logo', 'hero', 'fanart'):
        op.drop_index(f'unique_game_{_kind}_image', table_name='images')
    op.drop_index('ix_user_library_access_library_uuid', table_name='user_library_access')
    op.drop_index('ix_user_library_access_user_id', table_name='user_library_access')
    op.drop_index('ix_user_content_filters_user_id', table_name='user_content_filters')
    op.drop_index('ix_games_path_status', table_name='games')
    op.drop_index('ix_games_item_kind', table_name='games')
    op.drop_index('ix_games_rating', table_name='games')
    op.drop_index('ix_games_date_created', table_name='games')
    op.drop_index('ix_games_name', table_name='games')
    op.drop_index('ix_games_library_uuid', table_name='games')
    op.drop_index('ix_duplicate_fix_logs_matched_game', table_name='duplicate_fix_logs')
    op.drop_index('ix_duplicate_fix_logs_created_at', table_name='duplicate_fix_logs')
    op.drop_index('ix_client_devices_last_seen_at', table_name='client_devices')
    op.drop_index('idx_user_game_status_lookup', table_name='user_game_status')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_reactions_user_id'), table_name='chat_message_reactions')
    op.drop_index(op.f('ix_chat_message_reactions_message_id'), table_name='chat_message_reactions')
    op.drop_table('chat_message_reactions')
    op.drop_index(op.f('ix_chat_message_attachments_uploaded_by_user_id'), table_name='chat_message_attachments')
    op.drop_index(op.f('ix_chat_message_attachments_message_id'), table_name='chat_message_attachments')
    op.drop_index(op.f('ix_chat_message_attachments_channel_id'), table_name='chat_message_attachments')
    op.drop_table('chat_message_attachments')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_parent_message_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_channel_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_channel_members_user_id'), table_name='chat_channel_members')
    op.drop_index(op.f('ix_chat_channel_members_channel_id'), table_name='chat_channel_members')
    op.drop_table('chat_channel_members')
    op.drop_index(op.f('ix_user_owned_titles_user_id'), table_name='user_owned_titles')
    op.drop_index(op.f('ix_user_owned_titles_matched_game_uuid'), table_name='user_owned_titles')
    op.drop_table('user_owned_titles')
    op.drop_table('user_game_status')
    op.drop_index(op.f('ix_user_game_progress_user_id'), table_name='user_game_progress')
    op.drop_index(op.f('ix_user_game_progress_game_uuid'), table_name='user_game_progress')
    op.drop_table('user_game_progress')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_user_discover_impressions_user_id'), table_name='user_discover_impressions')
    op.drop_index(op.f('ix_user_discover_impressions_game_uuid'), table_name='user_discover_impressions')
    op.drop_table('user_discover_impressions')
    op.drop_index(op.f('ix_unmatched_folders_matched_game_uuid'), table_name='unmatched_folders')
    op.drop_table('unmatched_folders')
    op.drop_index('ix_reference_set_entries_set_norm', table_name='reference_set_entries')
    op.drop_index(op.f('ix_reference_set_entries_set_id'), table_name='reference_set_entries')
    op.drop_table('reference_set_entries')
    op.drop_index(op.f('ix_play_sessions_user_id'), table_name='play_sessions')
    op.drop_index(op.f('ix_play_sessions_game_uuid'), table_name='play_sessions')
    op.drop_table('play_sessions')
    op.drop_index(op.f('ix_pc_cheats_game_uuid'), table_name='pc_cheats')
    op.drop_table('pc_cheats')
    op.drop_table('images')
    op.drop_table('game_urls')
    op.drop_table('game_updates')
    op.drop_table('game_theme_association')
    op.drop_index(op.f('ix_game_similarity_neighbour_uuid'), table_name='game_similarity')
    op.drop_index(op.f('ix_game_similarity_game_uuid'), table_name='game_similarity')
    op.drop_table('game_similarity')
    op.drop_index(op.f('ix_game_servers_game_uuid'), table_name='game_servers')
    op.drop_table('game_servers')
    op.drop_index(op.f('ix_game_requests_user_id'), table_name='game_requests')
    op.drop_table('game_requests')
    op.drop_index(op.f('ix_game_related_media_game_uuid'), table_name='game_related_media')
    op.drop_table('game_related_media')
    op.drop_table('game_player_perspective_association')
    op.drop_table('game_platform_association')
    op.drop_table('game_multiplayer_mode_association')
    op.drop_table('game_genre_association')
    op.drop_table('game_game_mode_association')
    op.drop_table('game_extras')
    op.drop_table('game_developer_association')
    op.drop_table('game_collection_items')
    op.drop_index(op.f('ix_emulator_saves_user_id'), table_name='emulator_saves')
    op.drop_index(op.f('ix_emulator_saves_game_uuid'), table_name='emulator_saves')
    op.drop_table('emulator_saves')
    op.drop_table('download_requests')
    op.drop_index(op.f('ix_chat_space_members_user_id'), table_name='chat_space_members')
    op.drop_index(op.f('ix_chat_space_members_space_id'), table_name='chat_space_members')
    op.drop_table('chat_space_members')
    op.drop_index(op.f('ix_chat_space_invites_token'), table_name='chat_space_invites')
    op.drop_index(op.f('ix_chat_space_invites_space_id'), table_name='chat_space_invites')
    op.drop_table('chat_space_invites')
    op.drop_index(op.f('ix_chat_channels_space_id'), table_name='chat_channels')
    op.drop_table('chat_channels')
    op.drop_index(op.f('ix_user_taste_facets_user_id'), table_name='user_taste_facets')
    op.drop_table('user_taste_facets')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_table('user_library_access')
    op.drop_index(op.f('ix_user_friendships_user_id'), table_name='user_friendships')
    op.drop_index(op.f('ix_user_friendships_friend_user_id'), table_name='user_friendships')
    op.drop_table('user_friendships')
    op.drop_table('user_content_filters')
    op.drop_table('user_attract_mode_settings')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_store_accounts_user_id'), table_name='store_accounts')
    op.drop_table('store_accounts')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_reference_sets_region'), table_name='reference_sets')
    op.drop_index(op.f('ix_reference_sets_library_platform'), table_name='reference_sets')
    op.drop_table('reference_sets')
    op.drop_table('newsletters')
    op.drop_table('invite_tokens')
    op.drop_index(op.f('ix_games_file_sha1'), table_name='games')
    op.drop_index(op.f('ix_games_file_md5'), table_name='games')
    op.drop_index(op.f('ix_games_file_crc'), table_name='games')
    op.drop_table('games')
    op.drop_table('game_collections')
    op.drop_index(op.f('ix_duplicate_fix_logs_unmatched_folder_id'), table_name='duplicate_fix_logs')
    op.drop_index(op.f('ix_duplicate_fix_logs_matched_game_uuid'), table_name='duplicate_fix_logs')
    op.drop_table('duplicate_fix_logs')
    op.drop_index(op.f('ix_detail_layout_presets_user_id'), table_name='detail_layout_presets')
    op.drop_table('detail_layout_presets')
    op.drop_table('custom_emoji')
    op.drop_index(op.f('ix_client_devices_user_id'), table_name='client_devices')
    op.drop_table('client_devices')
    op.drop_table('chat_spaces')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_prefix'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_table('announcements')
    op.drop_table('whitelist')
    op.drop_table('users')
    op.drop_table('themes')
    op.drop_table('publishers')
    op.drop_table('player_perspectives')
    op.drop_table('platforms')
    op.drop_table('multiplayer_modes')
    op.drop_index(op.f('ix_libraries_group_name'), table_name='libraries')
    op.drop_table('libraries')
    op.drop_table('ignored_file_types')
    op.drop_index('ix_igdb_platform_releases_platform_region', table_name='igdb_platform_releases')
    op.drop_index(op.f('ix_igdb_platform_releases_library_platform'), table_name='igdb_platform_releases')
    op.drop_index(op.f('ix_igdb_platform_releases_igdb_game_id'), table_name='igdb_platform_releases')
    op.drop_table('igdb_platform_releases')
    op.drop_index('global_settings_singleton', table_name='global_settings')
    op.drop_table('global_settings')
    op.drop_table('genres')
    op.drop_table('game_modes')
    op.drop_index(op.f('ix_free_game_offers_store'), table_name='free_game_offers')
    op.drop_index(op.f('ix_free_game_offers_source'), table_name='free_game_offers')
    op.drop_index(op.f('ix_free_game_offers_active'), table_name='free_game_offers')
    op.drop_table('free_game_offers')
    op.drop_table('filters')
    op.drop_table('discovery_sections')
    op.drop_table('developers')
    op.drop_table('allowed_file_types')
    # ### end Alembic commands ###
